const createModel = require("./purchase2genericmodel");

module.exports = createModel("storegatepassds2", {
  gatepassno: { type: String, trim: true, index: true },
  direction: { type: String, trim: true },
  gatepasstype: { type: String, trim: true },
  sourcetype: { type: String, trim: true },
  qcno: { type: String, trim: true },
  poid: { type: String, trim: true, index: true },
  vendorid: { type: String, trim: true },
  vendorname: { type: String, trim: true },
  storeid: { type: String, trim: true },
  storename: { type: String, trim: true },
  receiveddate: { type: Date },
  receivedby: { type: String, trim: true },
  receivedbyemail: { type: String, trim: true },
  vehicle: { type: String, trim: true },
  vehicleno: { type: String, trim: true },
  drivername: { type: String, trim: true },
  drivercontact: { type: String, trim: true },
  challanno: { type: String, trim: true },
  challandate: { type: Date },
  invoiceno: { type: String, trim: true },
  billno: { type: String, trim: true },
  billdate: { type: Date },
  remarktype: { type: String, trim: true },
  attachmentlink: { type: String, trim: true },
  status: { type: String, trim: true, default: "Received" },
  remarks: { type: String, trim: true }
});
