const mongoose = require("mongoose");

const VisitorManagementSchema = new mongoose.Schema({
  colid: { type: Number, required: true, index: true },
  visitdate: { type: Date, index: true },
  gatepassno: { type: String, trim: true, index: true },
  visitorname: { type: String, trim: true, required: true },
  visitoremail: { type: String, trim: true },
  visitorphone: { type: String, trim: true },
  organization: { type: String, trim: true },
  visitoridtype: { type: String, trim: true },
  visitoridno: { type: String, trim: true },
  purpose: { type: String, trim: true },
  department: { type: String, trim: true },
  whomtomeet: { type: String, trim: true },
  whomtomeetemail: { type: String, trim: true, index: true },
  approvalstatus: { type: String, trim: true, default: "Pending", index: true },
  approvedby: { type: String, trim: true },
  approvedbyemail: { type: String, trim: true },
  approvedat: Date,
  approvalremarks: { type: String, trim: true },
  gate: { type: String, trim: true },
  passstatus: { type: String, trim: true, default: "Requested", index: true },
  issuedby: { type: String, trim: true },
  issuedbyemail: { type: String, trim: true },
  issuedat: Date,
  gatepassgenerated: { type: String, trim: true, default: "No", index: true },
  gatepassgeneratedby: { type: String, trim: true },
  gatepassgeneratedbyemail: { type: String, trim: true },
  gatepassgeneratedat: Date,
  intime: Date,
  outtime: Date,
  checkoutremarks: { type: String, trim: true },
  finalmeetingstatus: { type: String, trim: true, default: "Pending", index: true },
  meetingdetails: { type: String, trim: true },
  meetingoutcome: { type: String, trim: true },
  meetingupdatedby: { type: String, trim: true },
  meetingupdatedbyemail: { type: String, trim: true },
  meetingupdatedat: Date,
  vehicletype: { type: String, trim: true },
  vehicleno: { type: String, trim: true },
  drivername: { type: String, trim: true },
  driverphone: { type: String, trim: true },
  itemsbrought: { type: String, trim: true },
  laptopserial: { type: String, trim: true },
  remarks: { type: String, trim: true },
  status: { type: String, trim: true, default: "Active", index: true },
  name: { type: String, trim: true },
  user: { type: String, trim: true }
}, { timestamps: true });

VisitorManagementSchema.index({ colid: 1, visitdate: 1, approvalstatus: 1, passstatus: 1, finalmeetingstatus: 1 });

module.exports = mongoose.models.visitormanagementds || mongoose.model("visitormanagementds", VisitorManagementSchema);
